import "remixicon/fonts/remixicon.css";
import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "tl-test",
    description: "Generated by create next app",
};

export default function RootLayout({
    // modal,
    children,
}: Readonly<{
    // modal: React.ReactNode;
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(inter.className, "dark:bg-neutral-950")}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="absolute top-5 right-5">
                        <ThemeToggle />
                    </div>
                    {/* {modal} */}
                    <main>{children}</main>
                </ThemeProvider>
            </body>
        </html>
    );
}
